export enum StudyComponent {
  NO_COMPONENT,
  MOODCHECKIN,
  GOOD_REASON,
  BAD_REASON,
  STUDY_SUMMARY,
}

export enum BreakComponent {
  NO_COMPONENT,
  MOODCHECKIN,
  ACTIVITIES,
  BREAK_SUMMARY,
}

export enum SettingComponent {
  NO_COMPONENT,
  SETTINGS,
  EXAMPHASE_OVERVIEW,
  GOOD_REASONS,
  BAD_REASONS,
  BREAK_ACTIVITIES,
}
